version: "3"
services:
  api:
    container_name: zfc-api
    image: zfc-api
    build: 
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
      - "9229:9229"