FROM node:16-alpine

WORKDIR /app

COPY ["package.json","package-lock.json","tsconfig.json","tsconfig.build.json","./"]

RUN npm install 

COPY ["./src","./src"]

ENV PORT=5000

EXPOSE 5000

EXPOSE 9229

CMD ["npm","run","start:dev"]