version: "3"
services:
  api:
    container_name: zfc-api
    image: zfc-api
    build: 
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
      - "9229:9229"
    
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password # REMOVE IN PROD
      restart: always
      volumes:
        - ./mysql-data:/var/lib/mysql # UPDATE IN PROD
      env_file:
        - .env
      # environment:
      #   MYSQL_ROOT_PASSWORD: zfc-stuff # CHANGE
      #   MYSQL_DATABASE: zfc